# Generated by Django 3.0.3 on 2020-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=8, unique=True)),
                ('cuil', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, max_length=200, null=True)),
                ('date_deliver', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
