# Generated by Django 3.0.3 on 2020-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
