# Generated by Django 3.0.3 on 2020-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='order/pictures'),
        ),
    ]
