# Generated by Django 3.0.3 on 2020-04-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cuil',
        ),
    ]
